// *************************************************************************
//  This file is part of AcidMUD by Steaphan Greene
//
//  Copyright 1999-2022 Steaphan Greene <steaphan@gmail.com>
//
//  AcidMUD is free software; you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation; either version 3 of the License, or
//  (at your option) any later version.
//
//  AcidMUD is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with AcidMUD (see the file named "COPYING");
//  If not, see <http://www.gnu.org/licenses/>.
//
// *************************************************************************

// @generated code file: Do not edit.  Edit update_skills.sh instead.

// clang-format off

#include <map>
#include <vector>

#include "stats.hpp"
#include "properties.hpp"
#include "utils.hpp"

std::map<uint32_t, int32_t> defaults = {
    {prhash("Acrobatics"), 1},
    {prhash("Acting"), 3},
    {prhash("Activate Juju"), 7},
    {prhash("Air Pistols"), 1},
    {prhash("Air Rifles"), 1},
    {prhash("Air Weaving"), 4},
    {prhash("Alchemy"), 4},
    {prhash("Amphibious Combat"), 4},
    {prhash("Archery"), 1},
    {prhash("Arctic Waraxe Martial Art"), 2},
    {prhash("Armoring"), 4},
    {prhash("Art"), 3},
    {prhash("Artificing"), 4},
    {prhash("Artificing, Star"), 4},
    {prhash("Assault Cannons"), 2},
    {prhash("Assault Rifles"), 1},
    {prhash("Ballista"), 6},
    {prhash("Bike"), 6},
    {prhash("Blacksmithing"), 4},
    {prhash("Blowgun"), 1},
    {prhash("Boat, Powered"), 4},
    {prhash("Boat, Row"), 2},
    {prhash("Boat, Sail"), 6},
    {prhash("Body Checking"), 0},
    {prhash("Bowyer"), 4},
    {prhash("Breath Weapon"), 1},
    {prhash("Buggy"), 6},
    {prhash("Cannon"), 4},
    {prhash("Car"), 6},
    {prhash("Carpentry"), 4},
    {prhash("Carromeleg - Tier I"), 0},
    {prhash("Carromeleg - Tier II"), 1},
    {prhash("Carromeleg - Tier III"), 2},
    {prhash("Carromeleg - Tier IV"), 3},
    {prhash("Carromeleg - Tier V"), 4},
    {prhash("Carromeleg - Tier VI"), 5},
    {prhash("Cart"), 6},
    {prhash("Catching"), 1},
    {prhash("Centering"), 5},
    {prhash("Climbing"), 2},
    {prhash("Clothier"), 4},
    {prhash("Communications"), 4},
    {prhash("Computer"), 4},
    {prhash("Computer Build/Repair"), 4},
    {prhash("Computer Targeting"), 4},
    {prhash("Conjuring"), 3},
    {prhash("Crossbow"), 1},
    {prhash("Cyber Data Manipulation"), 4},
    {prhash("Cyber Vehicle Operation"), 4},
    {prhash("Cycling"), 6},
    {prhash("Damage Control"), 4},
    {prhash("Damage Resistance"), 0},
    {prhash("Demolitions"), 4},
    {prhash("Diplomacy"), 3},
    {prhash("Diving"), 1},
    {prhash("Dodge"), 1},
    {prhash("Earth Weaving"), 2},
    {prhash("Electrical Build/Repair"), 4},
    {prhash("Electronics"), 4},
    {prhash("Enchanting"), 4},
    {prhash("Endurance"), 2},
    {prhash("Engineering"), 4},
    {prhash("Etiquette"), 3},
    {prhash("Evasion"), 1},
    {prhash("Finance"), 4},
    {prhash("Find Juju"), 5},
    {prhash("Fire Weaving"), 3},
    {prhash("First Aid"), 4},
    {prhash("Fixed-Wing Craft"), 6},
    {prhash("Fixed-Wing Drone"), 4},
    {prhash("Fletcher"), 4},
    {prhash("Flight"), 1},
    {prhash("Focusing"), 2},
    {prhash("Grappling"), 2},
    {prhash("Gunnery"), 4},
    {prhash("Half-Track"), 6},
    {prhash("Healing"), 4},
    {prhash("Heavy Lasers"), 2},
    {prhash("Heavy Projectors"), 2},
    {prhash("Heavy Rifles"), 2},
    {prhash("Helmsman, Star"), 4},
    {prhash("High-G Combat"), 4},
    {prhash("High-G Ops"), 4},
    {prhash("Hovercraft"), 6},
    {prhash("Hover Drone"), 4},
    {prhash("Hurling"), 2},
    {prhash("Identify Juju"), 4},
    {prhash("Interrogation"), 4},
    {prhash("Intimidation"), 5},
    {prhash("Jumping"), 2},
    {prhash("Kicking"), 1},
    {prhash("Knowledge"), 4},
    {prhash("Laser Pistols"), 1},
    {prhash("Laser Rifles"), 1},
    {prhash("Lasso"), 1},
    {prhash("Launch Weapons"), 4},
    {prhash("Leadership"), 3},
    {prhash("Leatherworking"), 4},
    {prhash("Lifting"), 2},
    {prhash("Long Blades"), 1},
    {prhash("Long Cleaves"), 1},
    {prhash("Long Crushing"), 1},
    {prhash("Long Flails"), 1},
    {prhash("Long Piercing"), 1},
    {prhash("Long Staves"), 1},
    {prhash("Low-G Combat"), 4},
    {prhash("Low-G Ops"), 4},
    {prhash("Lumberjack"), 2},
    {prhash("Machine Guns"), 2},
    {prhash("Machine Pistols"), 1},
    {prhash("Magic Manipulation"), 3},
    {prhash("Martial Arts, Elven"), 5},
    {prhash("Masonry"), 4},
    {prhash("Mechanical Build/Repair"), 4},
    {prhash("Mechanics"), 4},
    {prhash("Metalworking"), 4},
    {prhash("Mindcasting"), 5},
    {prhash("Mounted Air Pistols"), 1},
    {prhash("Mounted Archery"), 1},
    {prhash("Mounted Blades"), 1},
    {prhash("Mounted Blowgun"), 1},
    {prhash("Mounted Cleaves"), 1},
    {prhash("Mounted Crossbow"), 1},
    {prhash("Mounted Crushing"), 1},
    {prhash("Mounted Flails"), 1},
    {prhash("Mounted Hurling"), 1},
    {prhash("Mounted Laser Pistols"), 1},
    {prhash("Mounted Machine Pistols"), 1},
    {prhash("Mounted Nets"), 1},
    {prhash("Mounted Piercing"), 1},
    {prhash("Mounted Pistols"), 1},
    {prhash("Mounted Plasma Pistols"), 1},
    {prhash("Mounted Shot Pistols"), 1},
    {prhash("Mounted Slings"), 1},
    {prhash("Mounted SMGs"), 1},
    {prhash("Mounted Throwing, Aero"), 1},
    {prhash("Mounted Throwing, Non-Aero"), 1},
    {prhash("Mounted Whips"), 1},
    {prhash("Navigation"), 4},
    {prhash("Negotiation"), 3},
    {prhash("Nets"), 1},
    {prhash("Neural Interface"), 5},
    {prhash("Offhand Air Pistols"), 1},
    {prhash("Offhand Blades"), 1},
    {prhash("Offhand Cleaves"), 1},
    {prhash("Offhand Crossbow"), 1},
    {prhash("Offhand Crushing"), 1},
    {prhash("Offhand Flails"), 1},
    {prhash("Offhand Hurling"), 1},
    {prhash("Offhand Laser Pistols"), 1},
    {prhash("Offhand Machine Pistols"), 1},
    {prhash("Offhand Piercing"), 1},
    {prhash("Offhand Pistols"), 1},
    {prhash("Offhand Plasma Pistols"), 1},
    {prhash("Offhand Punching"), 1},
    {prhash("Offhand Shot Pistols"), 1},
    {prhash("Offhand SMGs"), 1},
    {prhash("Offhand Staves"), 1},
    {prhash("Offhand Throwing, Aero"), 1},
    {prhash("Offhand Throwing, Non-Aero"), 1},
    {prhash("Offhand Whips"), 1},
    {prhash("Perception"), 4},
    {prhash("Performance"), 3},
    {prhash("Pistols"), 1},
    {prhash("Plasma Cannons"), 2},
    {prhash("Plasma Pistols"), 1},
    {prhash("Plasma Rifles"), 1},
    {prhash("Power Distribution"), 4},
    {prhash("Power Suit"), 6},
    {prhash("Prepared Simple"), 5},
    {prhash("Punching"), 1},
    {prhash("Quickdraw"), 1},
    {prhash("Race Car"), 6},
    {prhash("Refine Juju"), 3},
    {prhash("Research"), 4},
    {prhash("Riding"), 1},
    {prhash("Rifles"), 1},
    {prhash("Ritual Conjuring"), 5},
    {prhash("Ritual Spellcasting"), 5},
    {prhash("Rod Targeting"), 1},
    {prhash("Rotorcraft"), 6},
    {prhash("Rotor Drone"), 4},
    {prhash("Running"), 2},
    {prhash("Saurian Line Attacking"), 2},
    {prhash("Security"), 4},
    {prhash("Seduction"), 3},
    {prhash("Self Artificing"), 3},
    {prhash("Sensors"), 4},
    {prhash("Shields"), 2},
    {prhash("Ship"), 1},
    {prhash("Ship, Powered"), 4},
    {prhash("Shipwright"), 4},
    {prhash("Short Blades"), 1},
    {prhash("Short Cleaves"), 1},
    {prhash("Short Crushing"), 1},
    {prhash("Short Flails"), 1},
    {prhash("Short Piercing"), 1},
    {prhash("Short Staves"), 1},
    {prhash("Shotguns"), 1},
    {prhash("Shot Pistols"), 1},
    {prhash("Skiing"), 1},
    {prhash("Sled"), 1},
    {prhash("Slings"), 1},
    {prhash("Smelting"), 4},
    {prhash("SMGs"), 1},
    {prhash("Snowmobile"), 6},
    {prhash("Spacecraft"), 4},
    {prhash("Spellcasting"), 3},
    {prhash("Spellcraft"), 4},
    {prhash("Spellcraft, Star"), 4},
    {prhash("Spell Preparation"), 4},
    {prhash("Spell Targeting"), 1},
    {prhash("Sprinting"), 1},
    {prhash("Staff Slings"), 1},
    {prhash("Staff Targeting"), 1},
    {prhash("Stealth"), 1},
    {prhash("Style"), 3},
    {prhash("Surgery"), 1},
    {prhash("Survival"), 4},
    {prhash("Swimming"), 1},
    {prhash("Swordsmithing"), 4},
    {prhash("Tactics"), 4},
    {prhash("Talismongery"), 5},
    {prhash("Teamster"), 3},
    {prhash("Throwing, Aero"), 1},
    {prhash("Throwing, Non-Aero"), 1},
    {prhash("Tracked Drone"), 4},
    {prhash("Tracked Vehicle"), 6},
    {prhash("Tracking"), 4},
    {prhash("Tractor"), 6},
    {prhash("Treatment"), 4},
    {prhash("Trike"), 6},
    {prhash("Two-Handed Blades"), 2},
    {prhash("Two-Handed Cleaves"), 2},
    {prhash("Two-Handed Crushing"), 2},
    {prhash("Two-Handed Flails"), 2},
    {prhash("Two-Handed Piercing"), 1},
    {prhash("Two-Handed Staves"), 1},
    {prhash("Underwater Combat"), 4},
    {prhash("Vectored Thrust"), 6},
    {prhash("Vectored Thrust Drone"), 4},
    {prhash("Verbal Interface"), 4},
    {prhash("Wand Targeting"), 1},
    {prhash("Water Weaving"), 1},
    {prhash("Wheeled Drone"), 4},
    {prhash("Whips"), 1},
    {prhash("Woodworking"), 4},
    {prhash("Zero-G Combat"), 4},
    {prhash("Zero-G Ops"), 4},
};

std::map<std::string, std::vector<uint32_t>> skcat = {
    {"Athletic Skills",
     {
         prhash("Acrobatics"),
         prhash("Catching"),
         prhash("Climbing"),
         prhash("Diving"),
         prhash("Dodge"),
         prhash("Evasion"),
         prhash("Flight"),
         prhash("Jumping"),
         prhash("Lifting"),
         prhash("Riding"),
         prhash("Running"),
         prhash("Skiing"),
         prhash("Sprinting"),
         prhash("Stealth"),
         prhash("Swimming"),
     }},
    {"Body-Based Skills",
     {
         prhash("Body Checking"),
         prhash("Carromeleg - Tier I"),
         prhash("Damage Resistance"),
     }},
    {"Build/Repair Skills",
     {
         prhash("Computer Build/Repair"),
         prhash("Electrical Build/Repair"),
         prhash("Mechanical Build/Repair"),
     }},
    {"Charisma-Based Skills",
     {
         prhash("Acting"),
         prhash("Art"),
         prhash("Carromeleg - Tier IV"),
         prhash("Conjuring"),
         prhash("Diplomacy"),
         prhash("Etiquette"),
         prhash("Fire Weaving"),
         prhash("Leadership"),
         prhash("Magic Manipulation"),
         prhash("Negotiation"),
         prhash("Performance"),
         prhash("Refine Juju"),
         prhash("Seduction"),
         prhash("Self Artificing"),
         prhash("Spellcasting"),
         prhash("Style"),
         prhash("Teamster"),
     }},
    {"Combat Environment Skills",
     {
         prhash("Amphibious Combat"),
         prhash("High-G Combat"),
         prhash("Low-G Combat"),
         prhash("Underwater Combat"),
         prhash("Zero-G Combat"),
     }},
    {"Creation Skills",
     {
         prhash("Armoring"),
         prhash("Blacksmithing"),
         prhash("Bowyer"),
         prhash("Carpentry"),
         prhash("Clothier"),
         prhash("Fletcher"),
         prhash("Leatherworking"),
         prhash("Lumberjack"),
         prhash("Masonry"),
         prhash("Metalworking"),
         prhash("Shipwright"),
         prhash("Smelting"),
         prhash("Swordsmithing"),
         prhash("Woodworking"),
     }},
    {"Cyberpunk Skills",
     {
         prhash("Acrobatics"),
         prhash("Acting"),
         prhash("Air Pistols"),
         prhash("Air Rifles"),
         prhash("Amphibious Combat"),
         prhash("Archery"),
         prhash("Art"),
         prhash("Assault Cannons"),
         prhash("Assault Rifles"),
         prhash("Bike"),
         prhash("Blowgun"),
         prhash("Boat, Powered"),
         prhash("Boat, Row"),
         prhash("Boat, Sail"),
         prhash("Body Checking"),
         prhash("Buggy"),
         prhash("Cannon"),
         prhash("Car"),
         prhash("Cart"),
         prhash("Catching"),
         prhash("Climbing"),
         prhash("Communications"),
         prhash("Computer"),
         prhash("Computer Build/Repair"),
         prhash("Computer Targeting"),
         prhash("Crossbow"),
         prhash("Cyber Data Manipulation"),
         prhash("Cyber Vehicle Operation"),
         prhash("Cycling"),
         prhash("Damage Control"),
         prhash("Damage Resistance"),
         prhash("Demolitions"),
         prhash("Diplomacy"),
         prhash("Diving"),
         prhash("Dodge"),
         prhash("Electrical Build/Repair"),
         prhash("Electronics"),
         prhash("Endurance"),
         prhash("Engineering"),
         prhash("Etiquette"),
         prhash("Evasion"),
         prhash("Finance"),
         prhash("First Aid"),
         prhash("Fixed-Wing Craft"),
         prhash("Grappling"),
         prhash("Gunnery"),
         prhash("Half-Track"),
         prhash("Healing"),
         prhash("Heavy Lasers"),
         prhash("Heavy Projectors"),
         prhash("Heavy Rifles"),
         prhash("High-G Combat"),
         prhash("High-G Ops"),
         prhash("Hovercraft"),
         prhash("Hurling"),
         prhash("Interrogation"),
         prhash("Intimidation"),
         prhash("Jumping"),
         prhash("Kicking"),
         prhash("Knowledge"),
         prhash("Laser Pistols"),
         prhash("Laser Rifles"),
         prhash("Lasso"),
         prhash("Launch Weapons"),
         prhash("Leadership"),
         prhash("Lifting"),
         prhash("Long Blades"),
         prhash("Long Cleaves"),
         prhash("Long Crushing"),
         prhash("Long Flails"),
         prhash("Long Piercing"),
         prhash("Long Staves"),
         prhash("Low-G Combat"),
         prhash("Low-G Ops"),
         prhash("Machine Guns"),
         prhash("Machine Pistols"),
         prhash("Mechanical Build/Repair"),
         prhash("Mechanics"),
         prhash("Mounted Air Pistols"),
         prhash("Mounted Archery"),
         prhash("Mounted Blades"),
         prhash("Mounted Blowgun"),
         prhash("Mounted Cleaves"),
         prhash("Mounted Crossbow"),
         prhash("Mounted Crushing"),
         prhash("Mounted Flails"),
         prhash("Mounted Hurling"),
         prhash("Mounted Laser Pistols"),
         prhash("Mounted Machine Pistols"),
         prhash("Mounted Nets"),
         prhash("Mounted Piercing"),
         prhash("Mounted Pistols"),
         prhash("Mounted Plasma Pistols"),
         prhash("Mounted Shot Pistols"),
         prhash("Mounted Slings"),
         prhash("Mounted SMGs"),
         prhash("Mounted Throwing, Aero"),
         prhash("Mounted Throwing, Non-Aero"),
         prhash("Mounted Whips"),
         prhash("Navigation"),
         prhash("Negotiation"),
         prhash("Nets"),
         prhash("Neural Interface"),
         prhash("Offhand Air Pistols"),
         prhash("Offhand Blades"),
         prhash("Offhand Cleaves"),
         prhash("Offhand Crossbow"),
         prhash("Offhand Crushing"),
         prhash("Offhand Flails"),
         prhash("Offhand Hurling"),
         prhash("Offhand Laser Pistols"),
         prhash("Offhand Machine Pistols"),
         prhash("Offhand Piercing"),
         prhash("Offhand Pistols"),
         prhash("Offhand Plasma Pistols"),
         prhash("Offhand Punching"),
         prhash("Offhand Shot Pistols"),
         prhash("Offhand SMGs"),
         prhash("Offhand Staves"),
         prhash("Offhand Throwing, Aero"),
         prhash("Offhand Throwing, Non-Aero"),
         prhash("Offhand Whips"),
         prhash("Perception"),
         prhash("Performance"),
         prhash("Pistols"),
         prhash("Plasma Cannons"),
         prhash("Plasma Pistols"),
         prhash("Plasma Rifles"),
         prhash("Power Distribution"),
         prhash("Power Suit"),
         prhash("Punching"),
         prhash("Quickdraw"),
         prhash("Race Car"),
         prhash("Research"),
         prhash("Riding"),
         prhash("Rifles"),
         prhash("Rotorcraft"),
         prhash("Running"),
         prhash("Security"),
         prhash("Seduction"),
         prhash("Sensors"),
         prhash("Shields"),
         prhash("Ship"),
         prhash("Ship, Powered"),
         prhash("Short Blades"),
         prhash("Short Cleaves"),
         prhash("Short Crushing"),
         prhash("Short Flails"),
         prhash("Short Piercing"),
         prhash("Short Staves"),
         prhash("Shotguns"),
         prhash("Shot Pistols"),
         prhash("Skiing"),
         prhash("Sled"),
         prhash("Slings"),
         prhash("SMGs"),
         prhash("Snowmobile"),
         prhash("Spacecraft"),
         prhash("Sprinting"),
         prhash("Staff Slings"),
         prhash("Stealth"),
         prhash("Style"),
         prhash("Surgery"),
         prhash("Survival"),
         prhash("Swimming"),
         prhash("Tactics"),
         prhash("Teamster"),
         prhash("Throwing, Aero"),
         prhash("Throwing, Non-Aero"),
         prhash("Tracked Vehicle"),
         prhash("Tracking"),
         prhash("Tractor"),
         prhash("Treatment"),
         prhash("Trike"),
         prhash("Two-Handed Blades"),
         prhash("Two-Handed Cleaves"),
         prhash("Two-Handed Crushing"),
         prhash("Two-Handed Flails"),
         prhash("Two-Handed Piercing"),
         prhash("Two-Handed Staves"),
         prhash("Underwater Combat"),
         prhash("Vectored Thrust"),
         prhash("Verbal Interface"),
         prhash("Whips"),
         prhash("Zero-G Combat"),
         prhash("Zero-G Ops"),
     }},
    {"Cyber Skills",
     {
         prhash("Cyber Data Manipulation"),
         prhash("Cyber Vehicle Operation"),
     }},
    {"Drone Piloting Skills",
     {
         prhash("Fixed-Wing Drone"),
         prhash("Hover Drone"),
         prhash("Rotor Drone"),
         prhash("Tracked Drone"),
         prhash("Vectored Thrust Drone"),
         prhash("Wheeled Drone"),
     }},
    {"Elven Martial Arts Skills",
     {
         prhash("Carromeleg - Tier I"),
         prhash("Carromeleg - Tier II"),
         prhash("Carromeleg - Tier III"),
         prhash("Carromeleg - Tier IV"),
         prhash("Carromeleg - Tier V"),
         prhash("Carromeleg - Tier VI"),
     }},
    {"Expert Skills",
     {
         prhash("Perception"),
     }},
    {"FP Skills",
     {
         prhash("Air Weaving"),
         prhash("Earth Weaving"),
         prhash("Fire Weaving"),
         prhash("Water Weaving"),
     }},
    {"Hand-to-Hand Combat Skills",
     {
         prhash("Body Checking"),
         prhash("Grappling"),
         prhash("Kicking"),
         prhash("Punching"),
     }},
    {"Heavy Firearm Skills",
     {
         prhash("Assault Cannons"),
         prhash("Cannon"),
         prhash("Heavy Lasers"),
         prhash("Heavy Projectors"),
         prhash("Heavy Rifles"),
         prhash("Machine Guns"),
         prhash("Plasma Cannons"),
     }},
    {"Intelligence-Based Skills",
     {
         prhash("Air Weaving"),
         prhash("Alchemy"),
         prhash("Amphibious Combat"),
         prhash("Armoring"),
         prhash("Artificing"),
         prhash("Artificing, Star"),
         prhash("Blacksmithing"),
         prhash("Boat, Powered"),
         prhash("Bowyer"),
         prhash("Cannon"),
         prhash("Carpentry"),
         prhash("Carromeleg - Tier V"),
         prhash("Clothier"),
         prhash("Communications"),
         prhash("Computer"),
         prhash("Computer Build/Repair"),
         prhash("Computer Targeting"),
         prhash("Cyber Data Manipulation"),
         prhash("Cyber Vehicle Operation"),
         prhash("Damage Control"),
         prhash("Demolitions"),
         prhash("Electrical Build/Repair"),
         prhash("Electronics"),
         prhash("Enchanting"),
         prhash("Engineering"),
         prhash("Finance"),
         prhash("First Aid"),
         prhash("Fixed-Wing Drone"),
         prhash("Fletcher"),
         prhash("Gunnery"),
         prhash("Healing"),
         prhash("Helmsman, Star"),
         prhash("High-G Combat"),
         prhash("High-G Ops"),
         prhash("Hover Drone"),
         prhash("Identify Juju"),
         prhash("Interrogation"),
         prhash("Knowledge"),
         prhash("Launch Weapons"),
         prhash("Leatherworking"),
         prhash("Low-G Combat"),
         prhash("Low-G Ops"),
         prhash("Masonry"),
         prhash("Mechanical Build/Repair"),
         prhash("Mechanics"),
         prhash("Metalworking"),
         prhash("Navigation"),
         prhash("Perception"),
         prhash("Power Distribution"),
         prhash("Research"),
         prhash("Rotor Drone"),
         prhash("Security"),
         prhash("Sensors"),
         prhash("Ship, Powered"),
         prhash("Shipwright"),
         prhash("Smelting"),
         prhash("Spacecraft"),
         prhash("Spellcraft"),
         prhash("Spellcraft, Star"),
         prhash("Spell Preparation"),
         prhash("Survival"),
         prhash("Swordsmithing"),
         prhash("Tactics"),
         prhash("Tracked Drone"),
         prhash("Tracking"),
         prhash("Treatment"),
         prhash("Underwater Combat"),
         prhash("Vectored Thrust Drone"),
         prhash("Verbal Interface"),
         prhash("Wheeled Drone"),
         prhash("Woodworking"),
         prhash("Zero-G Combat"),
         prhash("Zero-G Ops"),
     }},
    {"Lost Martial Arts",
     {
         prhash("Arctic Waraxe Martial Art"),
     }},
    {"Magical Skills",
     {
         prhash("Air Weaving"),
         prhash("Alchemy"),
         prhash("Artificing"),
         prhash("Conjuring"),
         prhash("Earth Weaving"),
         prhash("Enchanting"),
         prhash("Fire Weaving"),
         prhash("Helmsman, Star"),
         prhash("Magic Manipulation"),
         prhash("Mindcasting"),
         prhash("Ritual Conjuring"),
         prhash("Ritual Spellcasting"),
         prhash("Rod Targeting"),
         prhash("Self Artificing"),
         prhash("Spellcasting"),
         prhash("Spellcraft"),
         prhash("Spell Targeting"),
         prhash("Staff Targeting"),
         prhash("Talismongery"),
         prhash("Wand Targeting"),
         prhash("Water Weaving"),
     }},
    {"Martial Arts Skills",
     {
         prhash("Martial Arts, Elven"),
     }},
    {"Medieval Skills",
     {
         prhash("Acrobatics"),
         prhash("Acting"),
         prhash("Activate Juju"),
         prhash("Air Weaving"),
         prhash("Alchemy"),
         prhash("Amphibious Combat"),
         prhash("Archery"),
         prhash("Arctic Waraxe Martial Art"),
         prhash("Armoring"),
         prhash("Art"),
         prhash("Artificing"),
         prhash("Artificing, Star"),
         prhash("Ballista"),
         prhash("Blacksmithing"),
         prhash("Blowgun"),
         prhash("Boat, Row"),
         prhash("Boat, Sail"),
         prhash("Body Checking"),
         prhash("Bowyer"),
         prhash("Breath Weapon"),
         prhash("Cannon"),
         prhash("Carpentry"),
         prhash("Carromeleg - Tier I"),
         prhash("Carromeleg - Tier II"),
         prhash("Carromeleg - Tier III"),
         prhash("Carromeleg - Tier IV"),
         prhash("Carromeleg - Tier V"),
         prhash("Carromeleg - Tier VI"),
         prhash("Catching"),
         prhash("Centering"),
         prhash("Climbing"),
         prhash("Clothier"),
         prhash("Conjuring"),
         prhash("Crossbow"),
         prhash("Damage Resistance"),
         prhash("Diplomacy"),
         prhash("Diving"),
         prhash("Dodge"),
         prhash("Earth Weaving"),
         prhash("Enchanting"),
         prhash("Endurance"),
         prhash("Engineering"),
         prhash("Prepared Intermediate"),
         prhash("Prepared Primary"),
         prhash("Prepared Basic"),
         prhash("Etiquette"),
         prhash("Evasion"),
         prhash("Find Juju"),
         prhash("Fire Weaving"),
         prhash("Fletcher"),
         prhash("Flight"),
         prhash("Focusing"),
         prhash("Grappling"),
         prhash("Healing"),
         prhash("Helmsman, Star"),
         prhash("High-G Combat"),
         prhash("Hurling"),
         prhash("Identify Juju"),
         prhash("Interrogation"),
         prhash("Intimidation"),
         prhash("Jumping"),
         prhash("Kicking"),
         prhash("Knowledge"),
         prhash("Lasso"),
         prhash("Leadership"),
         prhash("Leatherworking"),
         prhash("Lifting"),
         prhash("Long Blades"),
         prhash("Long Cleaves"),
         prhash("Long Crushing"),
         prhash("Long Flails"),
         prhash("Long Piercing"),
         prhash("Long Staves"),
         prhash("Low-G Combat"),
         prhash("Lumberjack"),
         prhash("Magic Manipulation"),
         prhash("Martial Arts, Elven"),
         prhash("Masonry"),
         prhash("Mechanics"),
         prhash("Metalworking"),
         prhash("Mindcasting"),
         prhash("Mounted Archery"),
         prhash("Mounted Blades"),
         prhash("Mounted Blowgun"),
         prhash("Mounted Cleaves"),
         prhash("Mounted Crossbow"),
         prhash("Mounted Crushing"),
         prhash("Mounted Flails"),
         prhash("Mounted Hurling"),
         prhash("Mounted Nets"),
         prhash("Mounted Piercing"),
         prhash("Mounted Slings"),
         prhash("Mounted Throwing, Aero"),
         prhash("Mounted Throwing, Non-Aero"),
         prhash("Mounted Whips"),
         prhash("Navigation"),
         prhash("Negotiation"),
         prhash("Nets"),
         prhash("Offhand Blades"),
         prhash("Offhand Cleaves"),
         prhash("Offhand Crossbow"),
         prhash("Offhand Crushing"),
         prhash("Offhand Flails"),
         prhash("Offhand Hurling"),
         prhash("Offhand Piercing"),
         prhash("Offhand Punching"),
         prhash("Offhand Staves"),
         prhash("Offhand Throwing, Aero"),
         prhash("Offhand Throwing, Non-Aero"),
         prhash("Offhand Whips"),
         prhash("Perception"),
         prhash("Performance"),
         prhash("Prepared Simple"),
         prhash("Punching"),
         prhash("Quickdraw"),
         prhash("Refine Juju"),
         prhash("Research"),
         prhash("Riding"),
         prhash("Ritual Conjuring"),
         prhash("Ritual Spellcasting"),
         prhash("Rod Targeting"),
         prhash("Running"),
         prhash("Saurian Line Attacking"),
         prhash("Security"),
         prhash("Seduction"),
         prhash("Self Artificing"),
         prhash("Shields"),
         prhash("Ship"),
         prhash("Shipwright"),
         prhash("Short Blades"),
         prhash("Short Cleaves"),
         prhash("Short Crushing"),
         prhash("Short Flails"),
         prhash("Short Piercing"),
         prhash("Short Staves"),
         prhash("Skiing"),
         prhash("Sled"),
         prhash("Slings"),
         prhash("Smelting"),
         prhash("Spellcasting"),
         prhash("Spellcraft"),
         prhash("Spellcraft, Star"),
         prhash("Spell Preparation"),
         prhash("Spell Targeting"),
         prhash("Sprinting"),
         prhash("Staff Slings"),
         prhash("Staff Targeting"),
         prhash("Stealth"),
         prhash("Style"),
         prhash("Survival"),
         prhash("Swimming"),
         prhash("Swordsmithing"),
         prhash("Tactics"),
         prhash("Talismongery"),
         prhash("Teamster"),
         prhash("Throwing, Aero"),
         prhash("Throwing, Non-Aero"),
         prhash("Tracking"),
         prhash("Two-Handed Blades"),
         prhash("Two-Handed Cleaves"),
         prhash("Two-Handed Crushing"),
         prhash("Two-Handed Flails"),
         prhash("Two-Handed Piercing"),
         prhash("Two-Handed Staves"),
         prhash("Underwater Combat"),
         prhash("Wand Targeting"),
         prhash("Water Weaving"),
         prhash("Whips"),
         prhash("Woodworking"),
         prhash("Zero-G Combat"),
     }},
    {"Melee-Combat Skills",
     {
         prhash("Long Blades"),
         prhash("Long Cleaves"),
         prhash("Long Crushing"),
         prhash("Long Flails"),
         prhash("Long Piercing"),
         prhash("Long Staves"),
         prhash("Offhand Blades"),
         prhash("Offhand Cleaves"),
         prhash("Offhand Crushing"),
         prhash("Offhand Flails"),
         prhash("Offhand Piercing"),
         prhash("Offhand Staves"),
         prhash("Shields"),
         prhash("Short Blades"),
         prhash("Short Cleaves"),
         prhash("Short Crushing"),
         prhash("Short Flails"),
         prhash("Short Piercing"),
         prhash("Short Staves"),
         prhash("Two-Handed Blades"),
         prhash("Two-Handed Cleaves"),
         prhash("Two-Handed Crushing"),
         prhash("Two-Handed Flails"),
         prhash("Two-Handed Piercing"),
         prhash("Two-Handed Staves"),
     }},
    {"Modern Skills",
     {
         prhash("Acrobatics"),
         prhash("Acting"),
         prhash("Air Pistols"),
         prhash("Air Rifles"),
         prhash("Amphibious Combat"),
         prhash("Archery"),
         prhash("Art"),
         prhash("Assault Cannons"),
         prhash("Assault Rifles"),
         prhash("Bike"),
         prhash("Blowgun"),
         prhash("Boat, Powered"),
         prhash("Boat, Row"),
         prhash("Boat, Sail"),
         prhash("Body Checking"),
         prhash("Buggy"),
         prhash("Cannon"),
         prhash("Car"),
         prhash("Carpentry"),
         prhash("Cart"),
         prhash("Catching"),
         prhash("Climbing"),
         prhash("Communications"),
         prhash("Computer"),
         prhash("Computer Build/Repair"),
         prhash("Computer Targeting"),
         prhash("Crossbow"),
         prhash("Cycling"),
         prhash("Damage Control"),
         prhash("Damage Resistance"),
         prhash("Demolitions"),
         prhash("Diplomacy"),
         prhash("Diving"),
         prhash("Dodge"),
         prhash("Electrical Build/Repair"),
         prhash("Electronics"),
         prhash("Endurance"),
         prhash("Engineering"),
         prhash("Etiquette"),
         prhash("Evasion"),
         prhash("Finance"),
         prhash("First Aid"),
         prhash("Fixed-Wing Craft"),
         prhash("Grappling"),
         prhash("Gunnery"),
         prhash("Half-Track"),
         prhash("Healing"),
         prhash("Heavy Lasers"),
         prhash("Heavy Projectors"),
         prhash("Heavy Rifles"),
         prhash("High-G Combat"),
         prhash("Hovercraft"),
         prhash("Hurling"),
         prhash("Interrogation"),
         prhash("Intimidation"),
         prhash("Jumping"),
         prhash("Kicking"),
         prhash("Knowledge"),
         prhash("Laser Pistols"),
         prhash("Laser Rifles"),
         prhash("Lasso"),
         prhash("Launch Weapons"),
         prhash("Leadership"),
         prhash("Lifting"),
         prhash("Long Blades"),
         prhash("Long Cleaves"),
         prhash("Long Crushing"),
         prhash("Long Flails"),
         prhash("Long Piercing"),
         prhash("Long Staves"),
         prhash("Low-G Combat"),
         prhash("Lumberjack"),
         prhash("Machine Guns"),
         prhash("Machine Pistols"),
         prhash("Mechanical Build/Repair"),
         prhash("Mechanics"),
         prhash("Mounted Air Pistols"),
         prhash("Mounted Archery"),
         prhash("Mounted Blades"),
         prhash("Mounted Blowgun"),
         prhash("Mounted Cleaves"),
         prhash("Mounted Crossbow"),
         prhash("Mounted Crushing"),
         prhash("Mounted Flails"),
         prhash("Mounted Hurling"),
         prhash("Mounted Laser Pistols"),
         prhash("Mounted Machine Pistols"),
         prhash("Mounted Nets"),
         prhash("Mounted Piercing"),
         prhash("Mounted Pistols"),
         prhash("Mounted Plasma Pistols"),
         prhash("Mounted Shot Pistols"),
         prhash("Mounted Slings"),
         prhash("Mounted SMGs"),
         prhash("Mounted Throwing, Aero"),
         prhash("Mounted Throwing, Non-Aero"),
         prhash("Mounted Whips"),
         prhash("Navigation"),
         prhash("Negotiation"),
         prhash("Nets"),
         prhash("Offhand Air Pistols"),
         prhash("Offhand Blades"),
         prhash("Offhand Cleaves"),
         prhash("Offhand Crossbow"),
         prhash("Offhand Crushing"),
         prhash("Offhand Flails"),
         prhash("Offhand Hurling"),
         prhash("Offhand Laser Pistols"),
         prhash("Offhand Machine Pistols"),
         prhash("Offhand Piercing"),
         prhash("Offhand Pistols"),
         prhash("Offhand Plasma Pistols"),
         prhash("Offhand Punching"),
         prhash("Offhand Shot Pistols"),
         prhash("Offhand SMGs"),
         prhash("Offhand Staves"),
         prhash("Offhand Throwing, Aero"),
         prhash("Offhand Throwing, Non-Aero"),
         prhash("Offhand Whips"),
         prhash("Perception"),
         prhash("Performance"),
         prhash("Pistols"),
         prhash("Plasma Cannons"),
         prhash("Plasma Pistols"),
         prhash("Plasma Rifles"),
         prhash("Power Distribution"),
         prhash("Punching"),
         prhash("Quickdraw"),
         prhash("Race Car"),
         prhash("Research"),
         prhash("Riding"),
         prhash("Rifles"),
         prhash("Rotorcraft"),
         prhash("Running"),
         prhash("Security"),
         prhash("Seduction"),
         prhash("Sensors"),
         prhash("Shields"),
         prhash("Ship"),
         prhash("Ship, Powered"),
         prhash("Short Blades"),
         prhash("Short Cleaves"),
         prhash("Short Crushing"),
         prhash("Short Flails"),
         prhash("Short Piercing"),
         prhash("Short Staves"),
         prhash("Shotguns"),
         prhash("Shot Pistols"),
         prhash("Skiing"),
         prhash("Sled"),
         prhash("Slings"),
         prhash("SMGs"),
         prhash("Snowmobile"),
         prhash("Spacecraft"),
         prhash("Sprinting"),
         prhash("Staff Slings"),
         prhash("Stealth"),
         prhash("Style"),
         prhash("Surgery"),
         prhash("Survival"),
         prhash("Swimming"),
         prhash("Tactics"),
         prhash("Teamster"),
         prhash("Throwing, Aero"),
         prhash("Throwing, Non-Aero"),
         prhash("Tracked Vehicle"),
         prhash("Tracking"),
         prhash("Tractor"),
         prhash("Treatment"),
         prhash("Trike"),
         prhash("Two-Handed Blades"),
         prhash("Two-Handed Cleaves"),
         prhash("Two-Handed Crushing"),
         prhash("Two-Handed Flails"),
         prhash("Two-Handed Piercing"),
         prhash("Two-Handed Staves"),
         prhash("Underwater Combat"),
         prhash("Vectored Thrust"),
         prhash("Whips"),
         prhash("Zero-G Combat"),
         prhash("Zero-G Ops"),
     }},
    {"Mounted Melee-Combat Skills",
     {
         prhash("Mounted Blades"),
         prhash("Mounted Cleaves"),
         prhash("Mounted Crushing"),
         prhash("Mounted Flails"),
         prhash("Mounted Piercing"),
     }},
    {"Mounted Pistol Skills",
     {
         prhash("Mounted Air Pistols"),
         prhash("Mounted Laser Pistols"),
         prhash("Mounted Machine Pistols"),
         prhash("Mounted Pistols"),
         prhash("Mounted Plasma Pistols"),
         prhash("Mounted Shot Pistols"),
         prhash("Mounted SMGs"),
     }},
    {"Mounted Ranged-Combat Skills",
     {
         prhash("Mounted Archery"),
         prhash("Mounted Blowgun"),
         prhash("Mounted Crossbow"),
         prhash("Mounted Hurling"),
         prhash("Mounted Nets"),
         prhash("Mounted Slings"),
         prhash("Mounted Throwing, Aero"),
         prhash("Mounted Throwing, Non-Aero"),
         prhash("Mounted Whips"),
     }},
    {"Nature Skills",
     {
         prhash("Healing"),
         prhash("Navigation"),
         prhash("Survival"),
     }},
    {"Piloting Skills",
     {
         prhash("Bike"),
         prhash("Boat, Powered"),
         prhash("Boat, Row"),
         prhash("Boat, Sail"),
         prhash("Buggy"),
         prhash("Car"),
         prhash("Cart"),
         prhash("Cycling"),
         prhash("Fixed-Wing Craft"),
         prhash("Half-Track"),
         prhash("Hovercraft"),
         prhash("Power Suit"),
         prhash("Race Car"),
         prhash("Rotorcraft"),
         prhash("Ship"),
         prhash("Ship, Powered"),
         prhash("Sled"),
         prhash("Snowmobile"),
         prhash("Spacecraft"),
         prhash("Teamster"),
         prhash("Tracked Vehicle"),
         prhash("Tractor"),
         prhash("Trike"),
         prhash("Vectored Thrust"),
     }},
    {"Pistol Skills",
     {
         prhash("Air Pistols"),
         prhash("Laser Pistols"),
         prhash("Machine Pistols"),
         prhash("Offhand Air Pistols"),
         prhash("Offhand Laser Pistols"),
         prhash("Offhand Machine Pistols"),
         prhash("Offhand Pistols"),
         prhash("Offhand Plasma Pistols"),
         prhash("Offhand Shot Pistols"),
         prhash("Offhand SMGs"),
         prhash("Pistols"),
         prhash("Plasma Pistols"),
         prhash("Shot Pistols"),
         prhash("SMGs"),
     }},
    {"Quickness-Based Skills",
     {
         prhash("Acrobatics"),
         prhash("Air Pistols"),
         prhash("Air Rifles"),
         prhash("Archery"),
         prhash("Assault Rifles"),
         prhash("Blowgun"),
         prhash("Breath Weapon"),
         prhash("Carromeleg - Tier II"),
         prhash("Catching"),
         prhash("Crossbow"),
         prhash("Diving"),
         prhash("Dodge"),
         prhash("Evasion"),
         prhash("Flight"),
         prhash("Kicking"),
         prhash("Laser Pistols"),
         prhash("Laser Rifles"),
         prhash("Lasso"),
         prhash("Long Blades"),
         prhash("Long Cleaves"),
         prhash("Long Crushing"),
         prhash("Long Flails"),
         prhash("Long Piercing"),
         prhash("Long Staves"),
         prhash("Machine Pistols"),
         prhash("Mounted Air Pistols"),
         prhash("Mounted Archery"),
         prhash("Mounted Blades"),
         prhash("Mounted Blowgun"),
         prhash("Mounted Cleaves"),
         prhash("Mounted Crossbow"),
         prhash("Mounted Crushing"),
         prhash("Mounted Flails"),
         prhash("Mounted Hurling"),
         prhash("Mounted Laser Pistols"),
         prhash("Mounted Machine Pistols"),
         prhash("Mounted Nets"),
         prhash("Mounted Piercing"),
         prhash("Mounted Pistols"),
         prhash("Mounted Plasma Pistols"),
         prhash("Mounted Shot Pistols"),
         prhash("Mounted Slings"),
         prhash("Mounted SMGs"),
         prhash("Mounted Throwing, Aero"),
         prhash("Mounted Throwing, Non-Aero"),
         prhash("Mounted Whips"),
         prhash("Nets"),
         prhash("Offhand Air Pistols"),
         prhash("Offhand Blades"),
         prhash("Offhand Cleaves"),
         prhash("Offhand Crossbow"),
         prhash("Offhand Crushing"),
         prhash("Offhand Flails"),
         prhash("Offhand Hurling"),
         prhash("Offhand Laser Pistols"),
         prhash("Offhand Machine Pistols"),
         prhash("Offhand Piercing"),
         prhash("Offhand Pistols"),
         prhash("Offhand Plasma Pistols"),
         prhash("Offhand Punching"),
         prhash("Offhand Shot Pistols"),
         prhash("Offhand SMGs"),
         prhash("Offhand Staves"),
         prhash("Offhand Throwing, Aero"),
         prhash("Offhand Throwing, Non-Aero"),
         prhash("Offhand Whips"),
         prhash("Pistols"),
         prhash("Plasma Pistols"),
         prhash("Plasma Rifles"),
         prhash("Punching"),
         prhash("Quickdraw"),
         prhash("Riding"),
         prhash("Rifles"),
         prhash("Rod Targeting"),
         prhash("Ship"),
         prhash("Short Blades"),
         prhash("Short Cleaves"),
         prhash("Short Crushing"),
         prhash("Short Flails"),
         prhash("Short Piercing"),
         prhash("Short Staves"),
         prhash("Shotguns"),
         prhash("Shot Pistols"),
         prhash("Skiing"),
         prhash("Sled"),
         prhash("Slings"),
         prhash("SMGs"),
         prhash("Spell Targeting"),
         prhash("Sprinting"),
         prhash("Staff Slings"),
         prhash("Staff Targeting"),
         prhash("Stealth"),
         prhash("Surgery"),
         prhash("Swimming"),
         prhash("Throwing, Aero"),
         prhash("Throwing, Non-Aero"),
         prhash("Two-Handed Piercing"),
         prhash("Two-Handed Staves"),
         prhash("Wand Targeting"),
         prhash("Water Weaving"),
         prhash("Whips"),
     }},
    {"Ranged-Combat Skills",
     {
         prhash("Archery"),
         prhash("Blowgun"),
         prhash("Crossbow"),
         prhash("Hurling"),
         prhash("Lasso"),
         prhash("Nets"),
         prhash("Offhand Crossbow"),
         prhash("Offhand Hurling"),
         prhash("Offhand Throwing, Aero"),
         prhash("Offhand Throwing, Non-Aero"),
         prhash("Offhand Whips"),
         prhash("Slings"),
         prhash("Staff Slings"),
         prhash("Throwing, Aero"),
         prhash("Throwing, Non-Aero"),
         prhash("Whips"),
     }},
    {"Reaction-Based Skills",
     {
         prhash("Ballista"),
         prhash("Bike"),
         prhash("Boat, Sail"),
         prhash("Buggy"),
         prhash("Car"),
         prhash("Cart"),
         prhash("Cycling"),
         prhash("Fixed-Wing Craft"),
         prhash("Half-Track"),
         prhash("Hovercraft"),
         prhash("Power Suit"),
         prhash("Race Car"),
         prhash("Rotorcraft"),
         prhash("Snowmobile"),
         prhash("Tracked Vehicle"),
         prhash("Tractor"),
         prhash("Trike"),
         prhash("Vectored Thrust"),
     }},
    {"Rifle Skills",
     {
         prhash("Air Rifles"),
         prhash("Assault Rifles"),
         prhash("Laser Rifles"),
         prhash("Plasma Rifles"),
         prhash("Rifles"),
         prhash("Shotguns"),
     }},
    {"Sci-Fi Skills",
     {
         prhash("Verbal Interface"),
     }},
    {"Shadowrun Skills",
     {
         prhash("Acrobatics"),
         prhash("Acting"),
         prhash("Air Pistols"),
         prhash("Air Rifles"),
         prhash("Alchemy"),
         prhash("Amphibious Combat"),
         prhash("Archery"),
         prhash("Art"),
         prhash("Assault Cannons"),
         prhash("Assault Rifles"),
         prhash("Bike"),
         prhash("Blowgun"),
         prhash("Boat, Powered"),
         prhash("Boat, Row"),
         prhash("Boat, Sail"),
         prhash("Body Checking"),
         prhash("Breath Weapon"),
         prhash("Buggy"),
         prhash("Cannon"),
         prhash("Car"),
         prhash("Carromeleg - Tier I"),
         prhash("Carromeleg - Tier II"),
         prhash("Carromeleg - Tier III"),
         prhash("Carromeleg - Tier IV"),
         prhash("Carromeleg - Tier V"),
         prhash("Carromeleg - Tier VI"),
         prhash("Cart"),
         prhash("Catching"),
         prhash("Climbing"),
         prhash("Communications"),
         prhash("Computer"),
         prhash("Computer Build/Repair"),
         prhash("Computer Targeting"),
         prhash("Conjuring"),
         prhash("Crossbow"),
         prhash("Cyber Data Manipulation"),
         prhash("Cyber Vehicle Operation"),
         prhash("Cycling"),
         prhash("Damage Control"),
         prhash("Damage Resistance"),
         prhash("Demolitions"),
         prhash("Diplomacy"),
         prhash("Diving"),
         prhash("Dodge"),
         prhash("Electrical Build/Repair"),
         prhash("Electronics"),
         prhash("Enchanting"),
         prhash("Endurance"),
         prhash("Engineering"),
         prhash("Etiquette"),
         prhash("Evasion"),
         prhash("Finance"),
         prhash("First Aid"),
         prhash("Fixed-Wing Craft"),
         prhash("Fixed-Wing Drone"),
         prhash("Flight"),
         prhash("Grappling"),
         prhash("Gunnery"),
         prhash("Half-Track"),
         prhash("Healing"),
         prhash("Heavy Lasers"),
         prhash("Heavy Projectors"),
         prhash("Heavy Rifles"),
         prhash("High-G Combat"),
         prhash("High-G Ops"),
         prhash("Hovercraft"),
         prhash("Hover Drone"),
         prhash("Hurling"),
         prhash("Interrogation"),
         prhash("Intimidation"),
         prhash("Jumping"),
         prhash("Kicking"),
         prhash("Knowledge"),
         prhash("Laser Pistols"),
         prhash("Laser Rifles"),
         prhash("Lasso"),
         prhash("Launch Weapons"),
         prhash("Leadership"),
         prhash("Lifting"),
         prhash("Long Blades"),
         prhash("Long Cleaves"),
         prhash("Long Crushing"),
         prhash("Long Flails"),
         prhash("Long Piercing"),
         prhash("Long Staves"),
         prhash("Low-G Combat"),
         prhash("Low-G Ops"),
         prhash("Machine Guns"),
         prhash("Machine Pistols"),
         prhash("Mechanical Build/Repair"),
         prhash("Mechanics"),
         prhash("Mindcasting"),
         prhash("Mounted Air Pistols"),
         prhash("Mounted Archery"),
         prhash("Mounted Blades"),
         prhash("Mounted Blowgun"),
         prhash("Mounted Cleaves"),
         prhash("Mounted Crossbow"),
         prhash("Mounted Crushing"),
         prhash("Mounted Flails"),
         prhash("Mounted Hurling"),
         prhash("Mounted Laser Pistols"),
         prhash("Mounted Machine Pistols"),
         prhash("Mounted Nets"),
         prhash("Mounted Piercing"),
         prhash("Mounted Pistols"),
         prhash("Mounted Plasma Pistols"),
         prhash("Mounted Shot Pistols"),
         prhash("Mounted Slings"),
         prhash("Mounted SMGs"),
         prhash("Mounted Throwing, Aero"),
         prhash("Mounted Throwing, Non-Aero"),
         prhash("Mounted Whips"),
         prhash("Navigation"),
         prhash("Negotiation"),
         prhash("Nets"),
         prhash("Neural Interface"),
         prhash("Offhand Air Pistols"),
         prhash("Offhand Blades"),
         prhash("Offhand Cleaves"),
         prhash("Offhand Crossbow"),
         prhash("Offhand Crushing"),
         prhash("Offhand Flails"),
         prhash("Offhand Hurling"),
         prhash("Offhand Laser Pistols"),
         prhash("Offhand Machine Pistols"),
         prhash("Offhand Piercing"),
         prhash("Offhand Pistols"),
         prhash("Offhand Plasma Pistols"),
         prhash("Offhand Punching"),
         prhash("Offhand Shot Pistols"),
         prhash("Offhand SMGs"),
         prhash("Offhand Staves"),
         prhash("Offhand Throwing, Aero"),
         prhash("Offhand Throwing, Non-Aero"),
         prhash("Offhand Whips"),
         prhash("Perception"),
         prhash("Performance"),
         prhash("Pistols"),
         prhash("Plasma Cannons"),
         prhash("Plasma Pistols"),
         prhash("Plasma Rifles"),
         prhash("Power Distribution"),
         prhash("Power Suit"),
         prhash("Punching"),
         prhash("Quickdraw"),
         prhash("Race Car"),
         prhash("Research"),
         prhash("Riding"),
         prhash("Rifles"),
         prhash("Ritual Conjuring"),
         prhash("Ritual Spellcasting"),
         prhash("Rotorcraft"),
         prhash("Rotor Drone"),
         prhash("Running"),
         prhash("Security"),
         prhash("Seduction"),
         prhash("Sensors"),
         prhash("Shields"),
         prhash("Ship"),
         prhash("Ship, Powered"),
         prhash("Short Blades"),
         prhash("Short Cleaves"),
         prhash("Short Crushing"),
         prhash("Short Flails"),
         prhash("Short Piercing"),
         prhash("Short Staves"),
         prhash("Shotguns"),
         prhash("Shot Pistols"),
         prhash("Skiing"),
         prhash("Sled"),
         prhash("Slings"),
         prhash("SMGs"),
         prhash("Snowmobile"),
         prhash("Spacecraft"),
         prhash("Spellcasting"),
         prhash("Spellcraft"),
         prhash("Spell Targeting"),
         prhash("Sprinting"),
         prhash("Staff Slings"),
         prhash("Stealth"),
         prhash("Style"),
         prhash("Surgery"),
         prhash("Survival"),
         prhash("Swimming"),
         prhash("Tactics"),
         prhash("Talismongery"),
         prhash("Teamster"),
         prhash("Throwing, Aero"),
         prhash("Throwing, Non-Aero"),
         prhash("Tracked Drone"),
         prhash("Tracked Vehicle"),
         prhash("Tracking"),
         prhash("Tractor"),
         prhash("Treatment"),
         prhash("Trike"),
         prhash("Two-Handed Blades"),
         prhash("Two-Handed Cleaves"),
         prhash("Two-Handed Crushing"),
         prhash("Two-Handed Flails"),
         prhash("Two-Handed Piercing"),
         prhash("Two-Handed Staves"),
         prhash("Underwater Combat"),
         prhash("Vectored Thrust"),
         prhash("Vectored Thrust Drone"),
         prhash("Verbal Interface"),
         prhash("Wheeled Drone"),
         prhash("Whips"),
         prhash("Zero-G Combat"),
         prhash("Zero-G Ops"),
     }},
    {"Shamanistic Skills",
     {
         prhash("Activate Juju"),
         prhash("Find Juju"),
         prhash("Identify Juju"),
         prhash("Refine Juju"),
     }},
    {"Skill-Based Skills",
     {
         prhash("Activate Juju"),
         prhash("Prepared Intermediate"),
         prhash("Prepared Primary"),
         prhash("Prepared Basic"),
     }},
    {"Skills",
     {
         prhash("Acrobatics"),
         prhash("Acting"),
         prhash("Activate Juju"),
         prhash("Air Pistols"),
         prhash("Air Rifles"),
         prhash("Air Weaving"),
         prhash("Alchemy"),
         prhash("Amphibious Combat"),
         prhash("Archery"),
         prhash("Arctic Waraxe Martial Art"),
         prhash("Armoring"),
         prhash("Art"),
         prhash("Artificing"),
         prhash("Artificing, Star"),
         prhash("Assault Cannons"),
         prhash("Assault Rifles"),
         prhash("Ballista"),
         prhash("Bike"),
         prhash("Blacksmithing"),
         prhash("Blowgun"),
         prhash("Boat, Powered"),
         prhash("Boat, Row"),
         prhash("Boat, Sail"),
         prhash("Body Checking"),
         prhash("Bowyer"),
         prhash("Breath Weapon"),
         prhash("Buggy"),
         prhash("Cannon"),
         prhash("Car"),
         prhash("Carpentry"),
         prhash("Carromeleg - Tier I"),
         prhash("Carromeleg - Tier II"),
         prhash("Carromeleg - Tier III"),
         prhash("Carromeleg - Tier IV"),
         prhash("Carromeleg - Tier V"),
         prhash("Carromeleg - Tier VI"),
         prhash("Cart"),
         prhash("Catching"),
         prhash("Centering"),
         prhash("Climbing"),
         prhash("Clothier"),
         prhash("Communications"),
         prhash("Computer"),
         prhash("Computer Build/Repair"),
         prhash("Computer Targeting"),
         prhash("Conjuring"),
         prhash("Crossbow"),
         prhash("Cyber Data Manipulation"),
         prhash("Cyber Vehicle Operation"),
         prhash("Cycling"),
         prhash("Damage Control"),
         prhash("Damage Resistance"),
         prhash("Demolitions"),
         prhash("Diplomacy"),
         prhash("Diving"),
         prhash("Dodge"),
         prhash("Earth Weaving"),
         prhash("Electrical Build/Repair"),
         prhash("Electronics"),
         prhash("Enchanting"),
         prhash("Endurance"),
         prhash("Engineering"),
         prhash("Prepared Intermediate"),
         prhash("Prepared Primary"),
         prhash("Prepared Basic"),
         prhash("Etiquette"),
         prhash("Evasion"),
         prhash("Finance"),
         prhash("Find Juju"),
         prhash("Fire Weaving"),
         prhash("First Aid"),
         prhash("Fixed-Wing Craft"),
         prhash("Fixed-Wing Drone"),
         prhash("Fletcher"),
         prhash("Flight"),
         prhash("Focusing"),
         prhash("Grappling"),
         prhash("Gunnery"),
         prhash("Half-Track"),
         prhash("Healing"),
         prhash("Heavy Lasers"),
         prhash("Heavy Projectors"),
         prhash("Heavy Rifles"),
         prhash("Helmsman, Star"),
         prhash("High-G Combat"),
         prhash("High-G Ops"),
         prhash("Hovercraft"),
         prhash("Hover Drone"),
         prhash("Hurling"),
         prhash("Identify Juju"),
         prhash("Interrogation"),
         prhash("Intimidation"),
         prhash("Jumping"),
         prhash("Kicking"),
         prhash("Knowledge"),
         prhash("Laser Pistols"),
         prhash("Laser Rifles"),
         prhash("Lasso"),
         prhash("Launch Weapons"),
         prhash("Leadership"),
         prhash("Leatherworking"),
         prhash("Lifting"),
         prhash("Long Blades"),
         prhash("Long Cleaves"),
         prhash("Long Crushing"),
         prhash("Long Flails"),
         prhash("Long Piercing"),
         prhash("Long Staves"),
         prhash("Low-G Combat"),
         prhash("Low-G Ops"),
         prhash("Lumberjack"),
         prhash("Machine Guns"),
         prhash("Machine Pistols"),
         prhash("Magic Manipulation"),
         prhash("Martial Arts, Elven"),
         prhash("Masonry"),
         prhash("Mechanical Build/Repair"),
         prhash("Mechanics"),
         prhash("Metalworking"),
         prhash("Mindcasting"),
         prhash("Mounted Air Pistols"),
         prhash("Mounted Archery"),
         prhash("Mounted Blades"),
         prhash("Mounted Blowgun"),
         prhash("Mounted Cleaves"),
         prhash("Mounted Crossbow"),
         prhash("Mounted Crushing"),
         prhash("Mounted Flails"),
         prhash("Mounted Hurling"),
         prhash("Mounted Laser Pistols"),
         prhash("Mounted Machine Pistols"),
         prhash("Mounted Nets"),
         prhash("Mounted Piercing"),
         prhash("Mounted Pistols"),
         prhash("Mounted Plasma Pistols"),
         prhash("Mounted Shot Pistols"),
         prhash("Mounted Slings"),
         prhash("Mounted SMGs"),
         prhash("Mounted Throwing, Aero"),
         prhash("Mounted Throwing, Non-Aero"),
         prhash("Mounted Whips"),
         prhash("Navigation"),
         prhash("Negotiation"),
         prhash("Nets"),
         prhash("Neural Interface"),
         prhash("Offhand Air Pistols"),
         prhash("Offhand Blades"),
         prhash("Offhand Cleaves"),
         prhash("Offhand Crossbow"),
         prhash("Offhand Crushing"),
         prhash("Offhand Flails"),
         prhash("Offhand Hurling"),
         prhash("Offhand Laser Pistols"),
         prhash("Offhand Machine Pistols"),
         prhash("Offhand Piercing"),
         prhash("Offhand Pistols"),
         prhash("Offhand Plasma Pistols"),
         prhash("Offhand Punching"),
         prhash("Offhand Shot Pistols"),
         prhash("Offhand SMGs"),
         prhash("Offhand Staves"),
         prhash("Offhand Throwing, Aero"),
         prhash("Offhand Throwing, Non-Aero"),
         prhash("Offhand Whips"),
         prhash("Perception"),
         prhash("Performance"),
         prhash("Pistols"),
         prhash("Plasma Cannons"),
         prhash("Plasma Pistols"),
         prhash("Plasma Rifles"),
         prhash("Power Distribution"),
         prhash("Power Suit"),
         prhash("Prepared Simple"),
         prhash("Punching"),
         prhash("Quickdraw"),
         prhash("Race Car"),
         prhash("Refine Juju"),
         prhash("Research"),
         prhash("Riding"),
         prhash("Rifles"),
         prhash("Ritual Conjuring"),
         prhash("Ritual Spellcasting"),
         prhash("Rod Targeting"),
         prhash("Rotorcraft"),
         prhash("Rotor Drone"),
         prhash("Running"),
         prhash("Saurian Line Attacking"),
         prhash("Security"),
         prhash("Seduction"),
         prhash("Self Artificing"),
         prhash("Sensors"),
         prhash("Shields"),
         prhash("Ship"),
         prhash("Ship, Powered"),
         prhash("Shipwright"),
         prhash("Short Blades"),
         prhash("Short Cleaves"),
         prhash("Short Crushing"),
         prhash("Short Flails"),
         prhash("Short Piercing"),
         prhash("Short Staves"),
         prhash("Shotguns"),
         prhash("Shot Pistols"),
         prhash("Skiing"),
         prhash("Sled"),
         prhash("Slings"),
         prhash("Smelting"),
         prhash("SMGs"),
         prhash("Snowmobile"),
         prhash("Spacecraft"),
         prhash("Spellcasting"),
         prhash("Spellcraft"),
         prhash("Spellcraft, Star"),
         prhash("Spell Preparation"),
         prhash("Spell Targeting"),
         prhash("Sprinting"),
         prhash("Staff Slings"),
         prhash("Staff Targeting"),
         prhash("Stealth"),
         prhash("Style"),
         prhash("Surgery"),
         prhash("Survival"),
         prhash("Swimming"),
         prhash("Swordsmithing"),
         prhash("Tactics"),
         prhash("Talismongery"),
         prhash("Teamster"),
         prhash("Throwing, Aero"),
         prhash("Throwing, Non-Aero"),
         prhash("Tracked Drone"),
         prhash("Tracked Vehicle"),
         prhash("Tracking"),
         prhash("Tractor"),
         prhash("Treatment"),
         prhash("Trike"),
         prhash("Two-Handed Blades"),
         prhash("Two-Handed Cleaves"),
         prhash("Two-Handed Crushing"),
         prhash("Two-Handed Flails"),
         prhash("Two-Handed Piercing"),
         prhash("Two-Handed Staves"),
         prhash("Underwater Combat"),
         prhash("Vectored Thrust"),
         prhash("Vectored Thrust Drone"),
         prhash("Verbal Interface"),
         prhash("Wand Targeting"),
         prhash("Water Weaving"),
         prhash("Wheeled Drone"),
         prhash("Whips"),
         prhash("Woodworking"),
         prhash("Zero-G Combat"),
         prhash("Zero-G Ops"),
     }},
    {"Social Skills",
     {
         prhash("Acting"),
         prhash("Art"),
         prhash("Diplomacy"),
         prhash("Etiquette"),
         prhash("Interrogation"),
         prhash("Intimidation"),
         prhash("Leadership"),
         prhash("Negotiation"),
         prhash("Performance"),
         prhash("Seduction"),
         prhash("Style"),
     }},
    {"Specialized Skills",
     {
         prhash("High-G Ops"),
         prhash("Knowledge"),
         prhash("Low-G Ops"),
         prhash("Perception"),
         prhash("Quickdraw"),
         prhash("Research"),
         prhash("Tactics"),
         prhash("Tracking"),
         prhash("Zero-G Ops"),
     }},
    {"Specialty Skills",
     {
         prhash("Cyber Data Manipulation"),
         prhash("Cyber Vehicle Operation"),
         prhash("Research"),
     }},
    {"Star Magical Skills",
     {
         prhash("Artificing, Star"),
         prhash("Centering"),
         prhash("Prepared Intermediate"),
         prhash("Prepared Primary"),
         prhash("Prepared Basic"),
         prhash("Focusing"),
         prhash("Prepared Simple"),
         prhash("Spellcraft, Star"),
         prhash("Spell Preparation"),
     }},
    {"Star Martial Arts",
     {
         prhash("Saurian Line Attacking"),
     }},
    {"Strength-Based Skills",
     {
         prhash("Arctic Waraxe Martial Art"),
         prhash("Assault Cannons"),
         prhash("Boat, Row"),
         prhash("Carromeleg - Tier III"),
         prhash("Climbing"),
         prhash("Earth Weaving"),
         prhash("Endurance"),
         prhash("Focusing"),
         prhash("Grappling"),
         prhash("Heavy Lasers"),
         prhash("Heavy Projectors"),
         prhash("Heavy Rifles"),
         prhash("Hurling"),
         prhash("Jumping"),
         prhash("Lifting"),
         prhash("Lumberjack"),
         prhash("Machine Guns"),
         prhash("Plasma Cannons"),
         prhash("Running"),
         prhash("Saurian Line Attacking"),
         prhash("Shields"),
         prhash("Two-Handed Blades"),
         prhash("Two-Handed Cleaves"),
         prhash("Two-Handed Crushing"),
         prhash("Two-Handed Flails"),
     }},
    {"Technical Skills",
     {
         prhash("Communications"),
         prhash("Computer"),
         prhash("Damage Control"),
         prhash("Demolitions"),
         prhash("Electronics"),
         prhash("Engineering"),
         prhash("First Aid"),
         prhash("Mechanics"),
         prhash("Neural Interface"),
         prhash("Power Distribution"),
         prhash("Security"),
         prhash("Sensors"),
         prhash("Surgery"),
         prhash("Treatment"),
         prhash("Verbal Interface"),
     }},
    {"Weapon System Skills",
     {
         prhash("Computer Targeting"),
         prhash("Gunnery"),
         prhash("Launch Weapons"),
     }},
    {"Willpower-Based Skills",
     {
         prhash("Carromeleg - Tier VI"),
         prhash("Centering"),
         prhash("Find Juju"),
         prhash("Intimidation"),
         prhash("Martial Arts, Elven"),
         prhash("Mindcasting"),
         prhash("Neural Interface"),
         prhash("Prepared Simple"),
         prhash("Ritual Conjuring"),
         prhash("Ritual Spellcasting"),
         prhash("Talismongery"),
     }},
};

std::map<int32_t, uint32_t> weaponskills;
std::map<uint32_t, int32_t> weapontypes;

static int last_wtype = 0;
static void add_wts(uint32_t sk) {
  if (defaults.count(sk) == 0) {
    fprintf(
        stderr,
        "Warning: Tried to link weapon type %d to '%s' which isn't a skill.\n",
        last_wtype + 1,
        SkillName(sk).c_str());
    return;
  }
  ++last_wtype;
  weaponskills[last_wtype] = sk;
  weapontypes[sk] = last_wtype;
}

void init_skill_list() {
  add_wts(prhash("Air Pistols"));
  add_wts(prhash("Air Rifles"));
  add_wts(prhash("Archery"));
  add_wts(prhash("Assault Rifles"));
  add_wts(prhash("Blowgun"));
  add_wts(prhash("Body Checking"));
  add_wts(prhash("Crossbow"));
  add_wts(prhash("Grappling"));
  add_wts(prhash("Hurling"));
  add_wts(prhash("Kicking"));
  add_wts(prhash("Laser Pistols"));
  add_wts(prhash("Laser Rifles"));
  add_wts(prhash("Lasso"));
  add_wts(prhash("Long Blades"));
  add_wts(prhash("Long Cleaves"));
  add_wts(prhash("Long Crushing"));
  add_wts(prhash("Long Flails"));
  add_wts(prhash("Long Piercing"));
  add_wts(prhash("Long Staves"));
  add_wts(prhash("Machine Pistols"));
  add_wts(prhash("Mounted Air Pistols"));
  add_wts(prhash("Mounted Archery"));
  add_wts(prhash("Mounted Blades"));
  add_wts(prhash("Mounted Blowgun"));
  add_wts(prhash("Mounted Cleaves"));
  add_wts(prhash("Mounted Crossbow"));
  add_wts(prhash("Mounted Crushing"));
  add_wts(prhash("Mounted Flails"));
  add_wts(prhash("Mounted Hurling"));
  add_wts(prhash("Mounted Laser Pistols"));
  add_wts(prhash("Mounted Machine Pistols"));
  add_wts(prhash("Mounted Nets"));
  add_wts(prhash("Mounted Piercing"));
  add_wts(prhash("Mounted Pistols"));
  add_wts(prhash("Mounted Plasma Pistols"));
  add_wts(prhash("Mounted Shot Pistols"));
  add_wts(prhash("Mounted Slings"));
  add_wts(prhash("Mounted SMGs"));
  add_wts(prhash("Mounted Throwing, Aero"));
  add_wts(prhash("Mounted Throwing, Non-Aero"));
  add_wts(prhash("Mounted Whips"));
  add_wts(prhash("Nets"));
  add_wts(prhash("Offhand Air Pistols"));
  add_wts(prhash("Offhand Blades"));
  add_wts(prhash("Offhand Cleaves"));
  add_wts(prhash("Offhand Crossbow"));
  add_wts(prhash("Offhand Crushing"));
  add_wts(prhash("Offhand Flails"));
  add_wts(prhash("Offhand Hurling"));
  add_wts(prhash("Offhand Laser Pistols"));
  add_wts(prhash("Offhand Machine Pistols"));
  add_wts(prhash("Offhand Piercing"));
  add_wts(prhash("Offhand Pistols"));
  add_wts(prhash("Offhand Plasma Pistols"));
  add_wts(prhash("Offhand Shot Pistols"));
  add_wts(prhash("Offhand SMGs"));
  add_wts(prhash("Offhand Staves"));
  add_wts(prhash("Offhand Throwing, Aero"));
  add_wts(prhash("Offhand Throwing, Non-Aero"));
  add_wts(prhash("Offhand Whips"));
  add_wts(prhash("Pistols"));
  add_wts(prhash("Plasma Pistols"));
  add_wts(prhash("Plasma Rifles"));
  add_wts(prhash("Punching"));
  add_wts(prhash("Rifles"));
  add_wts(prhash("Shields"));
  add_wts(prhash("Short Blades"));
  add_wts(prhash("Short Cleaves"));
  add_wts(prhash("Short Crushing"));
  add_wts(prhash("Short Flails"));
  add_wts(prhash("Short Piercing"));
  add_wts(prhash("Short Staves"));
  add_wts(prhash("Shotguns"));
  add_wts(prhash("Shot Pistols"));
  add_wts(prhash("Slings"));
  add_wts(prhash("SMGs"));
  add_wts(prhash("Staff Slings"));
  add_wts(prhash("Throwing, Aero"));
  add_wts(prhash("Throwing, Non-Aero"));
  add_wts(prhash("Two-Handed Blades"));
  add_wts(prhash("Two-Handed Cleaves"));
  add_wts(prhash("Two-Handed Crushing"));
  add_wts(prhash("Two-Handed Flails"));
  add_wts(prhash("Two-Handed Piercing"));
  add_wts(prhash("Two-Handed Staves"));
  add_wts(prhash("Whips"));
}
// clang-format on
